
[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.run-local]
description = "Run binary crate locally with environment variables loaded from appropriate .env file under .local folder"
script = [
  '''
    echo "Workspace root: ${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}"
    echo "Crate dir: ${CARGO_MAKE_WORKING_DIRECTORY}"
    REL_PATH="${CARGO_MAKE_WORKING_DIRECTORY#"$CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY"}"
    ENV_FILE="${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/.local/${REL_PATH}/.env"
    if [ -f "$ENV_FILE" ]; then
      echo "Using env file: $ENV_FILE"
      set -a
      . "$ENV_FILE"
      set +a
    else
      echo "Warning: $ENV_FILE not found"
    fi

    cargo run --bin "${CARGO_MAKE_CRATE_NAME}"
    ''',
]
